sudo: required
service:
 - docker
before_install:
  - docker build -t lokeshsm/custom:v1.0 .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push lokeshsm/custom:v1.0
notifications:
 email:
   recipients:
     - lsakamoo@nyit.edu.com
   on_success: always
   on_failure: always
